#XPath that will be used for Robot Automation
loginInputUsername                         = '//input[@placeholder="Username"]'
loginInputPassword                         = '//input[@placeholder="Password"]'
loginSubmitBtn                             = '//button[@type="submit"]'
invalidLoginElement                        = '//body/div[@id="app"]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/p[1]'
invalidLoginWording                        = 'Invalid credentials'
menuAdminBtn                               = '//body/div[@id="app"]/div[1]/div[1]/aside[1]/nav[1]/div[2]/ul[1]/li[1]'
AddUserBtn                                 = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/button[1]'
AddUserRoleDropdown                        = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]'
AddUserStatusDropdown                      = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]'
AddUserPasswordInput                       = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[2]/div[1]/div[1]/div[1]/div[2]/input[1]'
AddUserPasswordConfirm                     = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[2]/input[1]'
AddUserUsernameInput                       = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[4]/div[1]/div[2]/input[1]'
AddUserEmployeeName                        = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/input[1]'
EmployeeNameField                          = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]'
AddUserSaveBtn                             = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[3]/button[2]'
AddUserSuccessMsg                          = '//body/div[@id="app"]/div[@id="oxd-toaster_1"]/div[1]/div[1]/div[2]/p[2]'
AddUserEmployeeSelect                      = '//body/div[@id="app"]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]'